export interface LocationOption {
  value: string;
  label: string;
}

export const COUNTRIES: LocationOption[] = [
  { value: "US", label: "United States" },
  { value: "PT", label: "Portugal" },
  { value: "GB", label: "United Kingdom" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "ES", label: "Spain" },
  { value: "IT", label: "Italy" },
  { value: "NL", label: "Netherlands" },
  { value: "BE", label: "Belgium" },
  { value: "CH", label: "Switzerland" },
  { value: "AT", label: "Austria" },
  { value: "IE", label: "Ireland" },
  { value: "SE", label: "Sweden" },
  { value: "NO", label: "Norway" },
  { value: "DK", label: "Denmark" },
  { value: "FI", label: "Finland" },
  { value: "PL", label: "Poland" },
  { value: "CZ", label: "Czech Republic" },
  { value: "HU", label: "Hungary" },
  { value: "RO", label: "Romania" },
  { value: "BR", label: "Brazil" },
  { value: "CA", label: "Canada" },
  { value: "AU", label: "Australia" },
];

export const US_STATES: LocationOption[] = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" },
];

export const PT_DISTRICTS: LocationOption[] = [
  { value: "Lisboa", label: "Lisboa" },
  { value: "Porto", label: "Porto" },
  { value: "Braga", label: "Braga" },
  { value: "Setúbal", label: "Setúbal" },
  { value: "Aveiro", label: "Aveiro" },
  { value: "Coimbra", label: "Coimbra" },
  { value: "Faro", label: "Faro" },
  { value: "Leiria", label: "Leiria" },
  { value: "Viseu", label: "Viseu" },
  { value: "Santarém", label: "Santarém" },
  { value: "Évora", label: "Évora" },
  { value: "Beja", label: "Beja" },
  { value: "Viana do Castelo", label: "Viana do Castelo" },
  { value: "Guarda", label: "Guarda" },
  { value: "Castelo Branco", label: "Castelo Branco" },
  { value: "Portalegre", label: "Portalegre" },
  { value: "Bragança", label: "Bragança" },
  { value: "Vila Real", label: "Vila Real" },
  { value: "Madeira", label: "Madeira" },
  { value: "Açores", label: "Açores" },
];

/** Returns regional options based on country code. Null = free text */
export function getRegionOptions(countryCode: string): LocationOption[] | null {
  if (countryCode === "US") return US_STATES;
  if (countryCode === "PT") return PT_DISTRICTS;
  return null;
}
