// prisma/seed.ts — Seed com 10 usuários + 10 listings para teste
import { PrismaClient } from "@prisma/client";
import * as bcrypt from "bcrypt";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // ─── Limpar dados existentes (ordem para respeitar FKs) ───
  await prisma.listingPhoto.deleteMany();
  await prisma.listing.deleteMany();
  await prisma.refreshToken.deleteMany();
  await prisma.passwordReset.deleteMany();
  await prisma.loginAttempt.deleteMany();
  await prisma.user.deleteMany();

  const passwordHash = await bcrypt.hash("Test@1234", 12);

  // ─── 10 Usuários ───
  const users = await Promise.all([
    prisma.user.create({
      data: {
        firstName: "Ana",
        lastName: "Silva",
        email: "ana@test.com",
        passwordHash,
        role: "host",
        status: "active",
        emailVerified: true,
        isVerified: true,
        preferredLang: "pt",
        nationality: "Brasileira",
        currentCity: "Orlando",
        currentCountry: "US",
        bio: "Anfitriã em Orlando há 3 anos. Adoro ajudar brasileiros recém-chegados!",
      },
    }),
    prisma.user.create({
      data: {
        firstName: "Carlos",
        lastName: "Santos",
        email: "carlos@test.com",
        passwordHash,
        role: "host",
        status: "active",
        emailVerified: true,
        isVerified: true,
        preferredLang: "pt",
        nationality: "Brasileira",
        currentCity: "Boston",
        currentCountry: "US",
        bio: "Moro em Boston desde 2019. Tenho quartos disponíveis perto da universidade.",
      },
    }),
    prisma.user.create({
      data: {
        firstName: "Maria",
        lastName: "Oliveira",
        email: "maria@test.com",
        passwordHash,
        role: "host",
        status: "active",
        emailVerified: true,
        isVerified: true,
        preferredLang: "pt",
        nationality: "Brasileira",
        currentCity: "Lisboa",
        currentCountry: "PT",
        bio: "Portuguesa-brasileira vivendo em Lisboa. Quartos no centro histórico!",
      },
    }),
    prisma.user.create({
      data: {
        firstName: "João",
        lastName: "Pereira",
        email: "joao@test.com",
        passwordHash,
        role: "host",
        status: "active",
        emailVerified: true,
        preferredLang: "pt",
        nationality: "Brasileira",
        currentCity: "Orlando",
        currentCountry: "US",
      },
    }),
    prisma.user.create({
      data: {
        firstName: "Fernanda",
        lastName: "Costa",
        email: "fernanda@test.com",
        passwordHash,
        role: "tenant",
        status: "active",
        emailVerified: true,
        preferredLang: "pt",
        nationality: "Brasileira",
        currentCity: "São Paulo",
        currentCountry: "BR",
      },
    }),
    prisma.user.create({
      data: {
        firstName: "Lucas",
        lastName: "Almeida",
        email: "lucas@test.com",
        passwordHash,
        role: "tenant",
        status: "active",
        emailVerified: true,
        preferredLang: "en",
        nationality: "Brasileira",
        currentCity: "Rio de Janeiro",
        currentCountry: "BR",
      },
    }),
    prisma.user.create({
      data: {
        firstName: "Beatriz",
        lastName: "Souza",
        email: "beatriz@test.com",
        passwordHash,
        role: "tenant",
        status: "active",
        emailVerified: true,
        preferredLang: "pt",
        nationality: "Brasileira",
        currentCity: "Belo Horizonte",
        currentCountry: "BR",
      },
    }),
    prisma.user.create({
      data: {
        firstName: "Rafael",
        lastName: "Lima",
        email: "rafael@test.com",
        passwordHash,
        role: "tenant",
        status: "active",
        emailVerified: true,
        preferredLang: "es",
        nationality: "Brasileira",
        currentCity: "Curitiba",
        currentCountry: "BR",
      },
    }),
    prisma.user.create({
      data: {
        firstName: "Camila",
        lastName: "Ferreira",
        email: "camila@test.com",
        passwordHash,
        role: "host",
        status: "active",
        emailVerified: true,
        isVerified: true,
        preferredLang: "pt",
        nationality: "Brasileira",
        currentCity: "Lisboa",
        currentCountry: "PT",
        bio: "Brasileira em Lisboa. Ajudo na adaptação e documentação!",
      },
    }),
    prisma.user.create({
      data: {
        firstName: "Diego",
        lastName: "Martins",
        email: "diego@test.com",
        passwordHash,
        role: "tenant",
        status: "active",
        emailVerified: true,
        preferredLang: "pt",
        nationality: "Brasileira",
        currentCity: "Recife",
        currentCountry: "BR",
      },
    }),
  ]);

  console.log(`✅ ${users.length} usuários criados`);

  const [ana, carlos, maria, joao, , , , , camila] = users;

  // ─── 10 Listings ───
  const listings = await Promise.all([
    // ── Orlando (4 quartos) ──
    prisma.listing.create({
      data: {
        hostId: ana.id,
        title: "Quarto aconchegante em Orlando – perto da Disney",
        description:
          "Quarto mobiliado em casa brasileira perto do International Drive. Wi-Fi incluso, ambiente familiar. Perfeito para quem está chegando nos EUA.",
        propertyType: "house",
        listingType: "private_room",
        status: "active",
        country: "US",
        state: "FL",
        city: "Orlando",
        neighborhood: "International Drive",
        zipCode: "32819",
        streetAddress: "1234 Palm Ave",
        roomSize: "medium",
        hasWindow: true,
        hasCloset: true,
        hasLock: true,
        isFurnished: true,
        bedType: "queen",
        bedCount: 1,
        bathroomType: "shared",
        kitchenAccess: "full",
        laundryAccess: "in_unit",
        parkingType: "included",
        pricePerMonth: 850,
        currency: "USD",
        securityDeposit: 850,
        utilitiesIncluded: true,
        internetIncluded: true,
        minimumStay: 3,
        availableFrom: new Date("2026-05-01"),
        allowsPets: "small_only",
        allowsSmoking: "no",
        allowsCouples: true,
        allowsChildren: false,
        allowsVisitors: "daytime_only",
        lgbtFriendly: true,
        totalRooms: 4,
        totalBathrooms: 2,
        currentOccupants: 2,
        hostLivesIn: true,
        hasContract: true,
        amenities: ["wifi", "ac", "tv", "microwave", "washer"],
        viewCount: 127,
        isFeatured: true,
      },
    }),
    prisma.listing.create({
      data: {
        hostId: ana.id,
        title: "Suite privativa com banheiro em Kissimmee",
        description:
          "Suite com banheiro privativo em condomínio fechado. Piscina no condomínio. 15 min da Disney. Ambiente seguro e tranquilo.",
        propertyType: "condo",
        listingType: "private_room",
        status: "active",
        country: "US",
        state: "FL",
        city: "Orlando",
        neighborhood: "Kissimmee",
        zipCode: "34746",
        streetAddress: "5678 Lake Blvd",
        roomSize: "large",
        hasWindow: true,
        hasCloset: true,
        hasLock: true,
        isFurnished: true,
        bedType: "king",
        bedCount: 1,
        bathroomType: "private_ensuite",
        kitchenAccess: "full",
        laundryAccess: "in_unit",
        parkingType: "included",
        pricePerMonth: 1200,
        currency: "USD",
        securityDeposit: 1200,
        utilitiesIncluded: true,
        internetIncluded: true,
        minimumStay: 6,
        availableFrom: new Date("2026-05-15"),
        allowsPets: "no",
        allowsSmoking: "no",
        allowsCouples: true,
        allowsChildren: true,
        allowsVisitors: "anytime",
        lgbtFriendly: true,
        hasPool: true,
        totalRooms: 3,
        totalBathrooms: 2,
        currentOccupants: 1,
        hostLivesIn: true,
        hasContract: true,
        amenities: ["wifi", "ac", "tv", "pool", "dishwasher", "microwave"],
        viewCount: 89,
        isFeatured: true,
      },
    }),
    prisma.listing.create({
      data: {
        hostId: joao.id,
        title: "Quarto econômico em Orlando – ideal para estudantes",
        description:
          "Quarto simples e limpo em casa compartilhada. Perto de pontos de ônibus. Ótimo custo-benefício para quem está começando.",
        propertyType: "house",
        listingType: "shared_room",
        status: "active",
        country: "US",
        state: "FL",
        city: "Orlando",
        neighborhood: "Pine Hills",
        zipCode: "32808",
        streetAddress: "910 Orange St",
        roomSize: "small",
        hasWindow: true,
        hasCloset: false,
        hasLock: false,
        isFurnished: false,
        bedType: "single",
        bedCount: 2,
        bathroomType: "shared",
        kitchenAccess: "limited",
        laundryAccess: "nearby",
        parkingType: "street",
        pricePerMonth: 450,
        currency: "USD",
        utilitiesIncluded: false,
        internetIncluded: true,
        minimumStay: 1,
        availableFrom: new Date("2026-04-20"),
        allowsPets: "no",
        allowsSmoking: "outside_only",
        allowsCouples: false,
        allowsChildren: false,
        allowsVisitors: "with_notice",
        lgbtFriendly: true,
        totalRooms: 5,
        totalBathrooms: 2,
        currentOccupants: 4,
        hostLivesIn: false,
        hasContract: false,
        amenities: ["wifi", "ac"],
        viewCount: 45,
      },
    }),
    prisma.listing.create({
      data: {
        hostId: joao.id,
        title: "Studio completo no centro de Orlando",
        description:
          "Studio completo com cozinha e banheiro privativos. No coração de Downtown Orlando, perto de restaurantes e transporte.",
        propertyType: "studio",
        listingType: "entire_place",
        status: "active",
        country: "US",
        state: "FL",
        city: "Orlando",
        neighborhood: "Downtown",
        zipCode: "32801",
        streetAddress: "200 Central Blvd, Apt 4B",
        roomSize: "large",
        hasWindow: true,
        hasCloset: true,
        hasLock: true,
        isFurnished: true,
        bedType: "double",
        bedCount: 1,
        bathroomType: "private_ensuite",
        kitchenAccess: "full",
        laundryAccess: "in_building",
        parkingType: "available_paid",
        pricePerMonth: 1500,
        currency: "USD",
        securityDeposit: 1500,
        parkingCost: 100,
        utilitiesIncluded: false,
        internetIncluded: true,
        utilitiesEstimate: 120,
        minimumStay: 6,
        availableFrom: new Date("2026-06-01"),
        allowsPets: "cats_only",
        allowsSmoking: "no",
        allowsCouples: true,
        allowsChildren: true,
        allowsVisitors: "anytime",
        lgbtFriendly: true,
        totalRooms: 1,
        totalBathrooms: 1,
        currentOccupants: 0,
        hostLivesIn: false,
        hasContract: true,
        contractType: "annual",
        amenities: [
          "wifi",
          "ac",
          "tv",
          "dishwasher",
          "microwave",
          "oven",
          "elevator",
        ],
        viewCount: 203,
        isFeatured: true,
      },
    }),

    // ── Boston (3 quartos) ──
    prisma.listing.create({
      data: {
        hostId: carlos.id,
        title: "Quarto mobiliado em Boston – perto do metrô",
        description:
          "Quarto em apartamento compartilhado em Allston. 5 min a pé da estação de metrô. Ideal para estudantes e trabalhadores.",
        propertyType: "apartment",
        listingType: "private_room",
        status: "active",
        country: "US",
        state: "MA",
        city: "Boston",
        neighborhood: "Allston",
        zipCode: "02134",
        streetAddress: "45 Harvard Ave, Apt 2",
        roomSize: "medium",
        hasWindow: true,
        hasCloset: true,
        hasLock: true,
        isFurnished: true,
        bedType: "double",
        bedCount: 1,
        bathroomType: "shared",
        kitchenAccess: "full",
        laundryAccess: "in_building",
        parkingType: "street",
        pricePerMonth: 1100,
        currency: "USD",
        securityDeposit: 1100,
        utilitiesIncluded: true,
        internetIncluded: true,
        minimumStay: 3,
        availableFrom: new Date("2026-05-01"),
        allowsPets: "no",
        allowsSmoking: "no",
        allowsCouples: false,
        allowsChildren: false,
        allowsVisitors: "daytime_only",
        lgbtFriendly: true,
        publicTransport: "Green Line B – 5 min walk",
        totalRooms: 3,
        totalBathrooms: 1,
        currentOccupants: 2,
        hostLivesIn: true,
        hasContract: true,
        amenities: ["wifi", "heating", "washer", "dryer"],
        viewCount: 76,
      },
    }),
    prisma.listing.create({
      data: {
        hostId: carlos.id,
        title: "Quarto com vista em Cambridge – Harvard Square",
        description:
          "Quarto amplo com vista para o rio Charles. A 10 min de Harvard e MIT. Ambiente acadêmico e seguro.",
        propertyType: "apartment",
        listingType: "private_room",
        status: "active",
        country: "US",
        state: "MA",
        city: "Boston",
        neighborhood: "Cambridge",
        zipCode: "02138",
        streetAddress: "120 Memorial Dr, Apt 5C",
        roomSize: "large",
        hasWindow: true,
        hasCloset: true,
        hasLock: true,
        isFurnished: true,
        bedType: "queen",
        bedCount: 1,
        bathroomType: "private_not_ensuite",
        kitchenAccess: "full",
        laundryAccess: "in_building",
        parkingType: "none",
        pricePerMonth: 1600,
        currency: "USD",
        securityDeposit: 1600,
        utilitiesIncluded: true,
        internetIncluded: true,
        minimumStay: 6,
        availableFrom: new Date("2026-06-01"),
        allowsPets: "no",
        allowsSmoking: "no",
        allowsCouples: true,
        allowsChildren: false,
        allowsVisitors: "anytime",
        lgbtFriendly: true,
        publicTransport: "Red Line – Harvard Station 8 min walk",
        totalRooms: 2,
        totalBathrooms: 1,
        currentOccupants: 1,
        hostLivesIn: true,
        hasContract: true,
        amenities: ["wifi", "heating", "ac", "dishwasher", "elevator"],
        viewCount: 152,
        isFeatured: true,
      },
    }),
    prisma.listing.create({
      data: {
        hostId: carlos.id,
        title: "Quarto compartilhado barato em Dorchester",
        description:
          "Quarto compartilhado em casa grande. Bairro tranquilo, boa vizinhança brasileira. Ótimo para quem chega sem documentos.",
        propertyType: "house",
        listingType: "shared_room",
        status: "active",
        country: "US",
        state: "MA",
        city: "Boston",
        neighborhood: "Dorchester",
        zipCode: "02125",
        streetAddress: "88 Adams St",
        roomSize: "medium",
        hasWindow: true,
        hasCloset: false,
        hasLock: false,
        isFurnished: true,
        bedType: "bunk_bed",
        bedCount: 2,
        bathroomType: "shared",
        kitchenAccess: "scheduled",
        laundryAccess: "in_unit",
        parkingType: "street",
        pricePerMonth: 550,
        currency: "USD",
        utilitiesIncluded: true,
        internetIncluded: true,
        minimumStay: 1,
        availableFrom: new Date("2026-04-25"),
        allowsPets: "no",
        allowsSmoking: "no",
        allowsCouples: false,
        allowsChildren: false,
        allowsVisitors: "no",
        lgbtFriendly: true,
        totalRooms: 6,
        totalBathrooms: 2,
        currentOccupants: 5,
        hostLivesIn: false,
        hasContract: false,
        amenities: ["wifi", "heating", "washer"],
        viewCount: 33,
      },
    }),

    // ── Lisboa (3 quartos) ──
    prisma.listing.create({
      data: {
        hostId: maria.id,
        title: "Quarto charmoso no Bairro Alto – Lisboa",
        description:
          "Quarto em apartamento histórico no Bairro Alto. Vida noturna, restaurantes e transporte na porta. Perfeito para jovens profissionais.",
        propertyType: "apartment",
        listingType: "private_room",
        status: "active",
        country: "PT",
        state: "Lisboa",
        city: "Lisboa",
        neighborhood: "Bairro Alto",
        zipCode: "1200-109",
        streetAddress: "Rua da Atalaia 42, 3º",
        roomSize: "small",
        hasWindow: true,
        hasCloset: true,
        hasLock: true,
        isFurnished: true,
        bedType: "double",
        bedCount: 1,
        bathroomType: "shared",
        kitchenAccess: "full",
        laundryAccess: "in_unit",
        parkingType: "none",
        pricePerMonth: 550,
        currency: "EUR",
        securityDeposit: 550,
        utilitiesIncluded: true,
        internetIncluded: true,
        minimumStay: 3,
        availableFrom: new Date("2026-05-01"),
        allowsPets: "cats_only",
        allowsSmoking: "no",
        allowsCouples: true,
        allowsChildren: false,
        allowsVisitors: "daytime_only",
        lgbtFriendly: true,
        publicTransport: "Elevador da Glória – 2 min",
        totalRooms: 3,
        totalBathrooms: 1,
        currentOccupants: 2,
        hostLivesIn: true,
        hasContract: true,
        amenities: ["wifi", "heating", "washer", "tv"],
        viewCount: 98,
      },
    }),
    prisma.listing.create({
      data: {
        hostId: maria.id,
        title: "Suite com varanda em Alfama – vista para o Tejo",
        description:
          "Suite com banheiro privativo e varanda com vista para o rio Tejo. No coração do bairro mais antigo de Lisboa. Patrimônio e cultura.",
        propertyType: "apartment",
        listingType: "private_room",
        status: "active",
        country: "PT",
        state: "Lisboa",
        city: "Lisboa",
        neighborhood: "Alfama",
        zipCode: "1100-012",
        streetAddress: "Beco do Azinhal 8, 2º",
        roomSize: "medium",
        hasWindow: true,
        hasCloset: true,
        hasLock: true,
        isFurnished: true,
        hasBalcony: true,
        bedType: "queen",
        bedCount: 1,
        bathroomType: "private_ensuite",
        kitchenAccess: "full",
        laundryAccess: "in_unit",
        parkingType: "none",
        pricePerMonth: 750,
        currency: "EUR",
        securityDeposit: 750,
        utilitiesIncluded: true,
        internetIncluded: true,
        minimumStay: 6,
        availableFrom: new Date("2026-06-01"),
        allowsPets: "no",
        allowsSmoking: "no",
        allowsCouples: true,
        allowsChildren: true,
        allowsVisitors: "anytime",
        lgbtFriendly: true,
        publicTransport: "Tram 28 – 1 min walk",
        totalRooms: 2,
        totalBathrooms: 2,
        currentOccupants: 1,
        hostLivesIn: true,
        hasContract: true,
        amenities: ["wifi", "heating", "washer", "tv", "balcony", "river_view"],
        viewCount: 215,
        isFeatured: true,
      },
    }),
    prisma.listing.create({
      data: {
        hostId: camila.id,
        title: "Quarto em coliving brasileiro em Arroios",
        description:
          "Coliving para brasileiros em Lisboa! Ambiente jovem, eventos semanais, tudo incluso. Perto do metrô Arroios e da Av. Almirante Reis.",
        propertyType: "apartment",
        listingType: "shared_room",
        status: "active",
        country: "PT",
        state: "Lisboa",
        city: "Lisboa",
        neighborhood: "Arroios",
        zipCode: "1150-022",
        streetAddress: "Rua Morais Soares 55, 1º",
        roomSize: "medium",
        hasWindow: true,
        hasCloset: true,
        hasLock: true,
        isFurnished: true,
        bedType: "single",
        bedCount: 2,
        bathroomType: "shared",
        kitchenAccess: "full",
        laundryAccess: "in_unit",
        parkingType: "none",
        pricePerMonth: 400,
        currency: "EUR",
        securityDeposit: 400,
        utilitiesIncluded: true,
        internetIncluded: true,
        minimumStay: 1,
        availableFrom: new Date("2026-04-20"),
        allowsPets: "no",
        allowsSmoking: "no",
        allowsCouples: false,
        allowsChildren: false,
        allowsVisitors: "with_notice",
        lgbtFriendly: true,
        prefersBrazilian: true,
        publicTransport: "Metro Arroios – 3 min walk",
        totalRooms: 4,
        totalBathrooms: 2,
        currentOccupants: 5,
        hostLivesIn: false,
        hasContract: true,
        amenities: ["wifi", "heating", "washer", "dryer", "tv", "coworking"],
        viewCount: 67,
      },
    }),
  ]);

  console.log(`✅ ${listings.length} listings criados`);
  console.log("");
  console.log("📍 Orlando: 4 quartos ($450–$1500)");
  console.log("📍 Boston: 3 quartos ($550–$1600)");
  console.log("📍 Lisboa: 3 quartos (€400–€750)");
  console.log("");
  console.log("🔑 Login de teste: qualquer email acima com senha Test@1234");
  console.log(
    "   Hosts: ana@test.com, carlos@test.com, maria@test.com, joao@test.com, camila@test.com",
  );
  console.log(
    "   Tenants: fernanda@test.com, lucas@test.com, beatriz@test.com, rafael@test.com, diego@test.com",
  );
  console.log("");
  console.log("✨ Seed completo!");
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
